### ISSUE TITLE
Not working in Firefox/Safari if dateTo includes GMT+0300

### ISSUE THREAD

**Issue by danbruegge** [Tosunami/react-date-countdown-timer#2]
In Firefox and Safari there is this issue from your example where the numbers are displayed with `NaN`, if `dateTo="2023-01-01 00:00:00 GMT+0300"` includes `GMT+0300`.

Removing `GMT+0300` it will get it working in Firefox and Safari.

Example: https://codesandbox.io/s/7j613m8omj

**Comment by Tosunami** [comment]
Turns out Chrome is more flexible understanding date strings. Example changed
